server:
  port: ${PORT:9001}
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-stacktrace: never

spring:

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  #   base de datos posta
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5433/scholarium}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: ${JWT_EXPIRATION_MS:1800000}
  refresh-expiration-ms: ${JWT_REFRESH_EXPIRATION_MS:604800000}
  # 7 días en ms = 7 * 24 * 60 * 60 * 1000

google:
  client-id: ${GOOGLE_CLIENT_ID}

# Para activar el Trace
logging:
  level:
    root: INFO

app:
  cors:
    allowed-origins: ${CORS_ORIGINS:http://localhost:5173}